apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: supersonic-subatomic-java
  name: supersonic-subatomic-java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: supersonic-subatomic-java
  template:
    metadata:
      labels:
        app: supersonic-subatomic-java
    spec:
      nodeSelector:
        failure-domain.beta.kubernetes.io/zone: us-east-2a
      containers:
      - name: supersonic-subatomic-java
        image: quay.io/burrsutter/quarked:1.0.0
        ports:
          - containerPort: 8080
        resources:
          requests:
            memory: "300Mi"
            cpu: "25m" # 1/4 core
          limits:
            memory: "400Mi"
            cpu: "100m" # 1 core
        livenessProbe:
          httpGet:
              port: 8080
              path: /
          initialDelaySeconds: 1
          periodSeconds: 5
          timeoutSeconds: 2
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 1
          periodSeconds: 3
