apiVersion: v1
kind: Service
metadata:
  name: supersonic-subatomic-java
  labels:
    app: supersonic-subatomic-java
spec:
  ports:
  - name: http
    port: 8080
  selector:
    app: supersonic-subatomic-java
  type: LoadBalancer
